# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Ah8KiibvSgX3GK726SdRBmTH7C4gmEW
"""

from bs4 import BeautifulSoup
import requests
import json
import pandas as pd

targetUrl = "https://www.nike.com/t/lebron-xx-x-mimi-plange-ceremony-basketball-shoes-RbklbC/FJ0725-801"
response = requests.get(targetUrl)

if response.status_code == 200:

    #pagina todo e o beatiful soup
    soup = BeautifulSoup(response.text, 'html.parser')
    formatted_html = soup.prettify()

    #pegar o nome do produto
    nomeTenis = soup.find('script', type='application/ld+json')
    dadoProduto = json.loads(nomeTenis.string)
    nome = dadoProduto.get('name')

    #pegar o preço do produto
    precoProduto = soup.find('script', type='application/ld+json')
    dadoPreco = json.loads(precoProduto.string)
    preco = dadoPreco['offers']['price']
    print("Nome do Tênis: ", nome,  "\nPreço do Tênis em dolar: ", preco)
    #print(formatted_html)

    #Criar e guardar as informações em um dataFrame
    data = {'Nome do Tênis': [nome], 'Preço em Dólar': [preco]}
    df = pd.DataFrame(data)
    df.to_csv('informacoesDoProduto.csv', index=False)


else:
    print("Erro na solicitação. Código de status HTTP:", response.status_code)

